README.md

bug: fix logo link

---

.cspell/library_terms.txt
.github/workflows/docs.yml
documentation/source/conf.py

Add documentation build runner.
Move coreax imports to after adding to path.
No

Add documentation runner

---

README.md

Add Python version, PyPI and beta badges.
No

feat: add Python version, PyPI and beta badges

---

CHANGELOG.md
coreax/__init__.py

Rename release 0.1.0-beta to 0.1.0
Yes. Any reference to v0.1.0-beta is no longer valid.

Rename release 0.1.0-beta to 0.1.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

Refs #400
This PR updates the issue templates for Coreax. The changes aim to improve the clarity and completeness of information we receive when issues are reported.
n/a
No.

docs: update the issue templates

---

.github/badges/coverage.json

closes #488
Delete disused coverage badge config. Replaced by a config in external Gist.
This PR gives a good way to test #488!
Test A: Coverage badge renders in README
No

Delete disused coverage badge config

---

.github/workflows/unittests.yml

Closes #549
- Feature
- Tests
Adds collection only checks of the integration tests.
The added command produces the expected output when ran locally. The workflow runs described fail (as expected) prior to merge of #548 .
No

feat: perform collection only checks on the integration tests

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/pre_commit_autoupdate.yml
.github/workflows/pre_commit_checks.yml
.github/workflows/unittests.yml
.readthedocs.yaml
CHANGELOG.md
pyproject.toml
requirements-doc.txt

Closes #555, closes #236
- Feature
Bumps support to include python 3.12
All existing tests pass.
No

feat: bump support to include python 3.12

---

documentation/source/conf.py

Closes #561
Suppress configuration cache warnings
N/A

fix: disable sphinx cache warning

---

coreax/kernel.py
coreax/util.py
tests/unit/test_metrics.py
tests/unit/test_util.py

Closes #565 
- Feature
- add the `pairwise` transform to enable code deduplication
- utilise pytest in `test_utils` to enable code deduplication
Existing unit test pass.
No

feat: add `pairwise` transform to utils.

---

documentation/source/index.rst

- Bugfix
Fixes JAX link which has be causing documentation build failure.
N/A

fix(docs): patch external reference change

---

coreax/kernel.py

Adds basic definitions to the kernel functions
NA

docs: added basic definitions for the included kernels

---

tests/integration/test_david_map_reduce_weighted.py
tests/integration/test_herding_basic.py
tests/integration/test_herding_basic_weighted.py
tests/integration/test_herding_refine.py
tests/integration/test_herding_stein_weighted.py
tests/integration/test_herding_stein_weighted_ssm.py
tests/integration/test_herding_with_approximate_gram_matrix.py
tests/integration/test_pounce.py
tests/integration/test_pounce_map_reduce.py
tests/integration/test_pounce_map_reduce_ssm.py

- Bugfix
- Tests
Comparisons to random were removed from the unit tests in #611. Here we extend the removal to the integration tests.
All tests pass.
No

fix(test): remove comparison against random

---

coreax/networks.py
coreax/score_matching.py
tests/unit/test_networks.py

- Feature
- Tests
Added option to vary number and size of hidden layers in ScoreNetwork and SlicedScoreMatching.
Small alterations to existing tests.

feature/variable-layer-size 

---

coreax/approximation.py
coreax/data.py
coreax/kernel.py
coreax/metrics.py
coreax/score_matching.py
coreax/solvers/base.py
coreax/solvers/composite.py
coreax/solvers/coresubset.py
coreax/util.py
coreax/weights.py
documentation/source/conf.py
examples/david_map_reduce_weighted.py
examples/herding_approximate_gram_matrix.py
examples/herding_basic.py
examples/herding_basic_weighted.py
examples/herding_paired_kernel.py
examples/herding_refine_weighted.py
examples/herding_stein_weighted.py
examples/herding_stein_weighted_ssm.py
examples/pounce.py
examples/pounce_map_reduce.py
examples/pounce_map_reduce_ssm.py
tests/unit/test_kernel.py
tests/unit/test_solvers.py

Replace | operator with Union and used Optional type.

refactor: removed pipe operator

---

coreax/metrics.py

Closes #648
All existing unit tests pass.

refactor: augmented unroll parameter to be consistent with block size

---

.cspell/library_terms.txt
pyproject.toml

Add Pyright to dev dependencies. Closes #678.
`pip install -e .[dev]` successfully installs Pyright.
No
N/A

Add pyright to dev dependencies

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
coreax/__init__.py

refs: #680, #681
Release branch for v0.2.1.
Change bug report template to use this version by default. Not the end of the world if someone forgets to update this next time.
Note: Do not close #681 automatically on merging.
No

Prepare release v0.2.1

---

CONTRIBUTING.md

closes: #694
Describe release procedure.
What we did for v0.2.1.
No

feat: describe release procedure

---

.cspell/custom_misc.txt
coreax/util.py
coreax/weights.py
tests/unit/test_util.py
tests/unit/test_weights.py

Refactored `weights.py` to be generic on data type.
Large refactor of `test_weights.py` to reduce code duplication for future solvers and to expand testing.

refactor: made weight solvers generic on data type

---

.github/workflows/coverage.yml
README.md

refs: #714
- Bugfix
Add new file to Gist if it doesn't already exist.
No
No

fix: add new file to Gist if doesn't already exist

---

coreax/kernels/base.py
coreax/kernels/scalar_valued.py
tests/unit/test_approximation.py
tests/unit/test_kernels.py

- Feature
- Tests
Added `__init_check__`'s to every kernel in `scalar_valued.py`.
Added additional tests to expand coverage.

Check kernel params, extend kernel test coverage

---

coreax/data.py

docs: made dimensions of feature and response clearer, fixed doc error

---

.copyright-template
.cspell/library_terms.txt
.pre-commit-config.yaml
coreax/coreset.py
coreax/score_matching.py
coreax/solvers/composite.py
documentation/source/ref_style.py
examples/pounce_map_reduce_ssm.py
pre_commit_hooks/check_copyright.py
pre_commit_hooks/require_ascii.py
tests/unit/test_coreset.py
tests/unit/test_score_matching.py
tests/unit/test_util.py

Added a pre-commit hook to check for copyright notices.
Added copyright notices to a couple of files that were missing one.
Closes #741.
Pre-commit hook passes, indicating all Python files have a copyright notice.
No.
N/A

Add pre-commit hook to check for copyright notices

---

.cspell/library_terms.txt
.github/workflows/performance.yml
coreax/util.py
tests/performance/__init__.py
tests/performance/cases/__init__.py
tests/performance/cases/basic_coresets.py
tests/performance/cases/normaliser.py
tests/performance/compare.py
tests/performance/run.py
tests/unit/test_coreset.py
tests/unit/test_util.py

Add a CI workflow for performance testing: 
* On each push to `main`, it records a set of performance metrics.
* On each push to a PR, it computes performance metrics and compares them the most recent recorded set of performance metrics from `main`, and then adds a comment to the PR with a summary of any significant differences.
Also makes a couple of changes to `jit_test`:
* Adds an optional normalisation factor, which is used to reduce variance from running the performance tests across different machines.
* `JITCompilableFunction`s now have an optional string name (and are named "Function 1", "Function 2", etc if `None` is given).
See usage at https://github.com/rg936672/coreax/pull/1 and https://gist.github.com/rg936672/094213d70dcc9c03ec49a81545627373.
No.
(Write …

Performance testing CI workflow

---

tests/performance/compare.py

- Bugfix
Fixes performance comparison, so that the comparison script now recognises existing performance data.
Should get a more sensible comment from the bot.
No
N/A

Fix comparison of performance data spec versions

---

documentation/source/conf.py
documentation/source/coreax/approximations.rst
documentation/source/coreax/coresets.rst
documentation/source/coreax/kernel.rst
documentation/source/coreax/least_squares.rst
documentation/source/coreax/metrics.rst
documentation/source/coreax/solvers.rst

Set documentation of private members to be false.

docs: removed documentation of private members

---

coreax/least_squares.py

Minor improvements to docstrings.
Compile docs and read.
No

Improve least_squares documentation

---

.github/workflows/performance.yml

- Bugfix
Should fix performance pipeline issues seen in #749.
See if the pipeline passes!
No

fix: use GH_TOKEN as well as GITHUB_TOKEN in performance pipeline

---

coreax/solvers/coresubset.py

removed `SizeWarning` and added warning to docs

docs: removed SizeWarning and added warning to docs

---

CONTRIBUTING.md

fix: fixed citation format

---

.github/workflows/performance.yml
tests/performance/compare.py

Performance review comments should now mention the commit hash and subject line. This helps identify which comment is which if there are multiple (e.g. due to multiple sequential pushes to a branch).
See the comment below!
No

Mention commit message in performance review

---

.pylintrc
coreax/score_matching.py
coreax/util.py
tests/unit/test_coreset.py

Pylint 3.3 just came out, and this causes a few new failures in CI. This PR fixes those.
Pre-commit now passes with the latest version of Pylint.
No.

refactor: fix complaints from new version of pylint (3.3.0)

---

pyproject.toml

Remove a repeated/redundant ruff.lint ignore rule.
N/A
No

fix: remove repeated/redundant ruff.lint ignore.

---

coreax/solvers/coresubset.py

One of the steps in the iteration was using the non-updated version of the approximation matrix.
- Bugfix
Line 471 of coresubset.py: approximation_matrix should be changed to updated_approximation_matrix. Currently the iteration of the algorithm is computed incorrectly.
Normal tests pass.
No.

fix: fix rpcholesky algorithm

---

pyproject.toml
uv.lock

- Feature
Added `jupyter` as a dev dependency.

chore: add jupyter dev dependency

---

CONTRIBUTING.md

Closes #833. Will hopefully avoid merge conflicts in the CHANGELOG during future releases.
N/A
No
N/A

docs: change release procedure so branch is merged sooner

---

CONTRIBUTING.md

docs: clarify in CONTRIBUTING.md who merges PRs

---

CHANGELOG.md
coreax/__init__.py

refs: #844
Release branch for v0.3.1.
As per release procedure.
Also:
1. Build wheel.
2. In a clean directory, install wheel.
3. Start Python interpreter.
4. Call `import coreax`.
5. Quit interpreter.
6. Install wheel[test].
7. Copy `test` folder from repo - not source code.
8. Run `pytest tests/unit`.
No

chore: tidy changelog for 0.3.1

---

.github/ISSUE_TEMPLATE/bug_report.yml
CONTRIBUTING.md

Add updating of Coreax version in bug report template to release procedure

---

.github/workflows/coverage.yml
.github/workflows/performance.yml
benchmark/mnist_benchmark.py
tests/coverage/__init__.py
tests/coverage/compare.py

closes: #890
Use similar approach to performance workflow. Coverage badge does not retain sufficient precision so create a new history of coverage data.
Existing tests pass as expected.
Temporarily commit a large code file to reduce the coverage.
No

Fail coverage workflow if coverage reduces

---

coreax/coreset.py
requirements-doc.txt
uv.lock

Ran uv sync and pushed, it fixes the current CI failures on main.
Existing tests pass as expected. No new tests have been introduced
New tests introduced with this change verify that...

chore: uv sync and push uv lock

---

.github/workflows/uv_lock_autoupdate.yml

- Bugfix
The requirements-docs fix from #956 wasn't applied to the autoupdate workflow, causing it to fail.
It hasn't. However, the command now matches the one used in .pre-commit-config.yaml`, so the workflow should pass next time.
No

fix: uv autoupdate requirements-doc check

---

CHANGELOG.md
coreax/coreset.py
tests/unit/test_coreset.py

Refs: #952
- Bugfix
Closes #952. (This was partially resolved in #943, but this PR fixes the underlying issue.)
Existing tests pass as expected. Added an extra test to ensure that the materialised coreset length remains consistent.
No.

fix: correct shape of unweighted_indices

---

.github/workflows/pyright.yml
documentation/source/conf.py
documentation/source/ref_style.py
pyproject.toml

- Bugfix
Fix Pyright complaints in documentation folder.
Run Pyright across whole repo.
Fix incorrect name on Pyright CI workflow.
Pyright passes loccally.
No

Fix Pyright in documentation folder and enable for whole repo

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
coreax/__init__.py

- Bugfix
Second take at v0.4.0 release branch. Has been reviewed already in #968 and #969.
No

Release v0.4.0 hotfixes

---

.readthedocs.yaml

See: https://docs.readthedocs.com/platform/stable/build-customization.html#support-git-lfs-large-file-storage
- Bugfix
Add the fix from https://docs.readthedocs.com/platform/stable/build-customization.html#support-git-lfs-large-file-storage to hopefully fix the missing images in the documentation.
It hasn't - RtD doesn't seem to be building on pull requests?
No

ci(docs): fix LFS in ReadTheDocs build
