gchq/coreax

.readthedocs.yaml

Updated `.readthedocs.yaml` to allow Sphinx builds to succeed despite warnings.
When `fail_on_warning` is `true`, the `-W` and `--keep-going` flags are passed (see [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning)). The build returns a non-zero exit code when these flags are passed, but a zero exit code when they are not.
No
n/a

Allowing Sphinx builds to succeed despite warnings

---

tests/unit/test_approximation.py
tests/unit/test_coresubset.py
tests/unit/test_score_matching.py

Refs: #177
- Tests
All unit tests have been checked, and comparisons of the sort `self.assertEqual(...)` have inputs in the order actual, then expected.
All unit test files searched through and altered where the order was found to be inconsistent. 
N/A

style: update unittest comparison order to be (actual, expected)

---

CHANGELOG.md
coreax/weights.py
documentation/source/quickstart.rst
documentation/source/snippets/kernel_herding_with_weighting.py
examples/david_map_reduce_weighted.py
examples/herding_stein_weighted.py
examples/herding_stein_weighted_ssm.py
tests/unit/test_weights.py

Closes #448 
- Any uses of `coreax.weights.MMD` will need to be replaced with `coreax.weights.MMDWeightsOptimiser`.
- Any uses of `coreax.weights.SBQ` will ned to be replaced with `coreax.weights.SBQWeightsOptimiser`.

[feat]: rename weights optimisers

---

coreax/weights.py

Refs: #298
Detail previously removed in the docstring of SBQ weights optimizer has been restored. See https://github.com/gchq/coreax/issues/298#issue-2052575006 for details.
N/A
N/A

docs: added detail back into SBQ weights docstring

---

.cspell/library_terms.txt
.github/badges/coverage.json
.github/workflows/coverage.yml
CHANGELOG.md
README.md

Create coverage badge.
Appended to coverage action. Extracts total coverage percentage, writes Endpoint JSON for shields.io then pushes commit using gh API.
Using gh API ensure bot commit is signed and does not need to sign the CLA separately. Badge is generated by shields.io using Endpoint.
Test A: Take URL from badge in README and replace `main` with `feature/additional_badges`, then paste into https://shields.io/badges/endpoint-badge and click `Execute`.
Test B: Edit coverage.yml to manually set coverage percentage. Badge changes colour and size accordingly.
No

Add coverage badge

---

.pre-commit-config.yaml

Closes #484
Improves the fail_fast behaviour in pre-commit to minimise the iteration count and time for pre-commit.
- Tests
Pre-commit will only fail fast if an error has been raised before getting to cspell or pylint
No

feat: improve pre-commit fail_fast behaviour

---

.github/workflows/pre_commit_autoupdate.yml

closes #505
- Bugfix
Copy the version of pre-commit config from main onto the chore branch, then run pre-commit autoupdate on the chore branch. This should avoid merge conflicts resulting from running autoupdate on main.
We want to run pre-commit autoupdate on the config from main, not whatever happens to already be on the chore branch.
Test A: Create two branches locally. Commit the same file with different contents to each of them. Run `git checkout branch1 filename`. The file on the target branch should now be a copy of that on the other branch.
No

fix: avoid merge conflicts if branch already exists

---

.pre-commit-config.yaml
pyproject.toml

closes #513
Update comment on pre-commit `fail_fast` to reflect behaviour change in v3.7.0. Add this version constraint to project dependencies.
As this does not affect the main codebase, only developer experience, I have not added this to the changelog.
Test A: GitHub runners pass
No

Update comment on fail_fast to reflect fixed bug in pre-commit

---

.cspell/library_terms.txt
.github/workflows/coverage.yml
README.md

closes #488
~~Use the approach of #480 to create a new PR to update the code coverage badge.~~
Use a GitHub Gist to store the coverage badge config. The Gist is updated automatically on every push to main.
This ensures the badge on main is up-to-date. Also prevents excess bot commits.
~~Not directly tested. Relying on minimal edits to code copied from elsewhere that has been tested as part of #435 and #480.~~ Cannot test properly until merge into main.
Copy of code tested in a private repo.
No

feat: update coverage badge only on merge to main

---

.cspell/library_terms.txt
.github/workflows/pre_commit_autoupdate.yml
CHANGELOG.md

refs: #495
Using an app token ensures GitHub workflows run automatically on created PR.
Also move schedule to 00:00 on Monday to mean updates are less stale for working week.
Depends on Git app being set up.
Test A: Similar set-up on a private repo.
No

Run GitHub workflow automatically after Pre-commit auto-update

---

README.md

Fixes the coverage badge URL. It now points to the latest commit.
- Bugfix
Test A: Manually checked the URL generates the expected badge
No

fix: update coverage badge URL

---

.pre-commit-config.yaml

refs: #513
Pre-commit was incorrectly terminating if ruff formatter fails; it should have been ruff linter.
No

fix: stop pre-commit if ruff linter fails

---

tests/unit/test_approximation.py

Closes #532
- Feature
- Tests
Refactors the tests in `test_approximation.py` to utilise pytest fixtures and parameterization.
The new tests pass.
Removes the `test_kernel_mean_approximator_creation` as this is implicitly tested by all the other tests.
Uses the same "almost_equal" tolerance for all approximators (pulls random down to the tolerance used in ANN and Nystrom).

feat: utilise pytest for `test_approximation`

---

.pre-commit-config.yaml

closes #540
The forbid-binary Pre-commit hook appears to be no longer maintained. Remove it as it's redundant with require-ascii hook. Apply require-ascii hook to all files.
Test A: Run Pre-commit on all files
No

Remove forbid-binary hook

---

tests/integration/test_herding_refine.py

- Bugfix
Fixes the import path so the following command succeeds `pytest tests/integration`.
Note: we do not run the integration tests in the GitHub workflows so this was not picked up when merged in #539. Pull #550 provides new checks that would pick up such a bug in any future pulls.

fix: use fully qualified path for herding_refine lookup

---

.cspell/library_terms.txt
pyproject.toml
requirements-dev.txt
requirements-test.txt
tests/unit/test_util.py

Closes #525
- Bugfix
- Tests
Handles the very rare failures of the `jit_test` test by utilising `pytest.mark.flaky` from `pytest-rerunfailures`, which re-runs the test on the event of a failure (up to three times).
Now uses pytest parameterisation such that each individual scenario can be re-run if failed, rather than re-running until every scenario passes at once (reducing the probability of continued failure after three re-runs).
Additionally, provides an explicit check to ensure the function is only traced once (the JIT compiled function is being called on the second call) to supplement the implicit checks performed in checked the timings.
The new/updated unit tests pass.
No.

fix: handle very rare `jit_test` test failures

---

documentation/source/references.bib

- Bugfix
The arxiv article referenced by `@huszar2016optimally` has been withdrawn as it is a duplicate of another article. This pull updates the reference so it points at the non-withdrawn version.
Old arxiv link: https://arxiv.org/abs/1408.2049
New arxiv link: https://arxiv.org/abs/1204.1664
N/A
No

fix: update reference to withdrawn article

---

tests/unit/test_refine.py

Closes #546
- Feature
- Tests
Reduces the LOC and enhances the modularity of the tests. This should help improve test consistency and reduce the implementation burden for testing any future additions to refine.py.
The new tests pass.
N/A

feat: utilise pytest for `test_refine`

---

.cspell/library_terms.txt
coreax/kernel.py
tests/unit/test_kernel.py

Closes #542
- Feature
- Tests
Significantly reduces the LOCs and enhances modularity of the tests. This should help improve test consistency and reduce the implementation burden for testing any future additions to `kernel.py`.
The new tests pass.
Removes the following redundant/ineffective tests:
- `test_approximator_valid`: test did not perform effective checks
- `test_stein_kernel_computation`: redundant overlap with `test_stein_kernel_element_computation`
- `test_stein_kernel_invalid_base_kernel_missing_divergence` and `test_stein_kernel_invalid_base_kernel_no_pytree` are replaced with a single check of `InvalidKernel`
Modifies the following logic:
- ~~`SteinKernel` now only checks on a call to `compute_elementwise` if the `base_kernel` attribute …

feat: utilise pytest for `test_kernel`

---

.cspell/custom_misc.txt
CHANGELOG.md
coreax/approximation.py
coreax/coresubset.py
coreax/kernel.py
coreax/reduction.py
coreax/refine.py
coreax/score_matching.py
coreax/util.py
documentation/source/conf.py
examples/herding_approximate_gram_matrix.py
tests/integration/test_herding_with_approximate_gram_matrix.py
tests/performance/test_coresubset.py
tests/unit/test_approximation.py
tests/unit/test_coresubset.py
tests/unit/test_kernel.py
tests/unit/test_reduction.py
tests/unit/test_refine.py
tests/unit/test_util.py

Closes #599
- Bugfix
- Feature
- Tests
Renames the `kernel_matrix_row_sum_mean` to the more concise Gramian row-mean, and utilises `jax.lax.scan` to provide more control over the block iterated computation of this quantity.
More comprehensive testing is now performed when checking the behaviour of various `block_size` (previously called `max_size`) values, when passed to `gramian_row_mean`. As a result, some other tests have become redundant, and have been removed (primarily in `test_coresubset.py`).
All tests pass
removed `{update,calculate}_kernel_matrix_row_sum` and `calculate_kernel_matrix_row_sum_mean`; replaced by calls to …

feat!: introduce Gramian row-mean

---

.cspell/custom_misc.txt
.pylintrc
coreax/__init__.py
coreax/coreset.py
coreax/data.py
tests/unit/test_coreset.py
tests/unit/test_data.py

Closes #518
- Feature
- Tests
As part of #581, it is necessary to decouple the coreset data-structures and solvers/reduction-strategies. The new `coreax.coreset.Coreset` and `coreax.coreset.Coresubset` data-structures introduced here facilitate this decoupling, such that the conceptual notion of a coreset better reflects our implementation. I.E. a coreset is a data-structure and a solver is a solver, the current implementation treats a coreset as both of these things.
Note: these new data-structures are currently unused. They will be used in an upcoming PR to fully address #581.
A new set of unit tests have been created for these new data-structures in `tests/unit/test_coreset.py`.
Additionally updates the new `coreax.data.Data` with `at_least{1,2}d` equinox converters and a `__len__` …

feat: add coreset and coresubset data structures

---

.pre-commit-config.yaml
pyproject.toml

Closes: #597
Replaces most pygrep hooks with ruff.
Only `use-type-annotations` is retained; ruff only supports this check for PYI files (PYI033).
CI runs as expected.
No

feat(CI): replace most pygrep hooks with ruff

---

coreax/util.py

- Bugfix
Ensures weights are greater than or equal to zero and sum to one. Fixes bug detailed in listed issue.
All tests pass.

fix negative weights

---

.github/workflows/coverage.yml

refs: #714
Rename coverage badge data file to coreax_coverage.json.
TODO after merging this PR: delete coreax.json from Gist. Therefore, do not automatically close this issue.
No
No

chore: rename coverage badge data file to coreax_coverage.json

---

CONTRIBUTING.md

Added a description of our deprecation requirements for Coreax to CONTRIBUTING.md. In short:
- Breaking changes must have a deprecation period of at least one minor release.
- If there isn't a straightforward alternative for users, such as if a function or class is removed entirely, the deprecation period must instead be at least two minor releases.
Closes #720.
N/A
No

Add deprecation period to CONTRIBUTING.md

---

CHANGELOG.md
coreax/score_matching.py
coreax/util.py
documentation/source/conf.py
tests/__init__.py

…default behaviour
- Feature
Fixed pyright complaints with SilentTQDM and made not printing default behaviour
All tests pass.

feat: fixed pyright complaints with SilentTQDM and made not printing default behaviour

---

CONTRIBUTING.md

closes: #771
In contributor guidelines: Mandate that GPU tests to be run prior to release.
View rendered MD.
No

Mandate that GPU tests to be run prior to release

---

tests/unit/test_util.py

Refs: #773
- Bugfix
- Tests
As of jax 0.4.33, XLA related errors are raised if we try to use large batch sizes of arrays in the test `test_sample_batch_indices_inter_row_uniqueness`. This test is really ensuring that, if we sample N batches of size M from K integers, then each of the N batches are unique. This is highly likely for a large K and comparatively small N, M. The pervious batch size used in the test causes issues with buffer sizes in jax 0.4.33, so I have instead kept the main purpose of the test, but altered the batch size and number of batches to avoid the buffer errors. This keeps the desired check but does not overload the JAX buffer.
Unittest passes.
N/A

bug: Fixed issue with large batch sizes causing XLA errors in JAX 0.4.33

---

coreax/score_matching.py
tests/unit/test_score_matching.py

Refs: #764
- Bugfix
Investigation into score matching slowdown has shown that using both JAX's `jnp.atleast_2d` and `coreax.data._atleast_2d_consistent` are consistent with desired results, but the former is faster when called a huge number of times (as is the case when one might want to use a Stein kernel). A comment has been added explaining this.
N/A
N/A

docs: Clarify usage of atleast_2d from JAX inside of score matching.

---

documentation/source/conf.py

closes #796 
Update URL of flax linen (was pointing at flax NNX).
Remove trailing slashes from URLs to silence warnings about inventories having moved.
Documentation compiles.
No

Redirect Intersphinx inventories

---

CHANGELOG.md
CONTRIBUTING.md
coreax/kernel.py
coreax/util.py
coreax/weights.py

- Removals
- Remove items slated for deprecation in v0.3.0 (closes #578)
- Deprecations now state what version they have been deprecated since
- Features deprecated in v0.3.0 (`coreax.kernel`, `coreax.util.median_heuristic`) are slated for removal in v0.4.0, not v0.3.0
N/A
No

Deprecation removals for v0.3.0

---

.cspell/custom_misc.txt
documentation/source/examples/analytical_kernel_herding.rst
documentation/source/index.rst
tests/unit/test_solvers.py

Refs: #786
Closes: #786 
- Tests
Kernel herding now has an analytical test (for the case where unique is set to true and when it is set to false) and these tests have been used to showcase to a user a minimal worked example in the documentation.
Two new tests added and pass.
N/A

tests: add analytic kernel herding tests.

---

.github/workflows/uv_lock_autoupdate.yml

- Bugfix
Passing the (base64-encoded) contents of `uv.lock` directly on the command line results in an `Argument list too long` error. As described in the [docs](https://cli.github.com/manual/gh_api), we can instead pass `--field content="@filename"` to get `gh` to read from the file `filename`, bypassing the issue.
I've tested this on my own fork, and it works correctly (modulo a few authentication changes I had to make to get it to run on the fork, but those shouldn't be relevant here.)
No
N/A

fix(ci): pass files in uv_lock_autoupdate by filename

---

CONTRIBUTING.md

Closes #828. Added instructions in CONTRIBUTING that PRs should modify the CHANGELOG and link to any issues that they close. 
I'm not 100% confident in the procedure here, but it's borne out of two aims I have for it:
- PRs should not have to add links to themselves in the CHANGELOG, as this requires you to make the PR first and then add a separate commit to link it. (As you don't know what the PR number is until you create it!)
- The final CHANGELOG should contain PR links, either instead of or in addition to the issue links.
Do comment if you disagree, though!
This may also want to wait for #823 to be merged, so that we can mention this in the PR template as well.
N/A
No
N/A

Add changelog guidelines to CONTRIBUTING.md

---

CHANGELOG.md
coreax/solvers/coresubset.py
tests/unit/test_solvers.py

- Bugfix
Make sure RPCholesky outputs a full coreset of `coreset_size` by falling back on random selection. Resolves #835.
- Tests pass
- No repeating points in the coreset, even if `coreset_size == num_data_points`. 
- The initial points before convergence coincide before and after the fix.
No.

fix: rpcholesky reverts to random selection after convergence

---

.cspell/library_terms.txt
CHANGELOG.md
coreax/metrics.py

`MMD^2` in the computation has been truncated to ensure it is non-negative.
- Bugfix
`MMD.compute` has been changed so that it returns 0 if precision error causes it to be negative.
The previous known case returns 0 instead of nan. 
No.

fix: mmd metric returning nan

---

CHANGELOG.md
coreax/solvers/recombination.py

- Bugfix
Closes #852. Closes #853. Fixes an incorrect update applied in the elimination step of the recombination solvers.
Existing tests pass as expected, even on a GPU machine.
No.

fix: numerical errors in GPU recombination

---

.github/workflows/coverage.yml
.github/workflows/performance.yml
CHANGELOG.md
README.md
requirements-doc.txt

Change coverage and performance workflows to direct output to coreax-metadata repo. Redirect coverage badge to read from this new location.
Fix coverage export to run under uv - was command not found.
Please also review the commits in coreax-metadata repo. https://github.com/[gchq/coreax-metadata](https://github.com/gchq/coreax-metadata)
Complexity: 5
**Leave the merge to the author. Data needs to be copied from the Gist to the metadata repo, which I won't do until this PR is ready and approved.**
- Temporarily adjust workflow to push coverage badge as part of PR CI. (I have squashed these commits - sorry!)
Yes to supporting infrastructure.
- Coverage badge endpoint is now at https://raw.githubusercontent.com/gchq/coreax-metadata/refs/heads/main/coverage/coreax_coverag …

Export coverage and performance data to metadata repo instead of gist

---

.pre-commit-config.yaml
CHANGELOG.md
tests/coverage/compare.py
tests/performance/compare.py

- Bugfix
The Pylint docs recommend against using Pylint as a pre-commit hook in the first place, but that if you do need to set `require_serial` to `true`. Otherwise, it might give inconsistent results on some checkers (such as `duplicate-code`) since the files that contain duplicate code might be analysed by two separate Pylint processes.
See: https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
Pre-commit still runs as expected; testing the effects directly is not easy but this should avoid inconsistent results on certain checkers.
No

Pylint pre-commit should not run in parallel

---

CHANGELOG.md
pyproject.toml
requirements-doc.txt
uv.lock

- Bugfix
Add lower bounds for all direct dependencies. These are largely just "whatever the most recent major version was", or most recent minor version for [0ver](https://0ver.org/) dependencies. Closes #807.
Existing tests pass as expected. This doesn't change which dependencies are installed when solving for the latest dependencies, but should prevent solvers from erroneously backtracking to early versions of our dependencies.
We don't actually test with our stated lower bounds - that's left for #918.
No.

Add lower bound for all direct dependencies

---

.github/workflows/pyright.yml
CHANGELOG.md
examples/coreset_in_model_pipeline.py
examples/david_map_reduce_weighted.py
examples/herding_approximate_gram_matrix.py
examples/herding_basic.py
examples/herding_basic_weighted.py
examples/herding_duo_composite_kernel.py
examples/herding_refine_weighted.py
examples/herding_stein_weighted.py
examples/herding_stein_weighted_ssm.py
examples/pounce.py
examples/pounce_map_reduce.py

- Bugfix
Closes #913.
Existing tests pass as expected.
`pyright examples` passes without errors.
Added a workflow that runs `pyright coreax examples` to ensure that both the main Coreax package and the example scripts continue to pass Pyright. (The main package was done in #906.)

Fix pyright errors in examples

---

CHANGELOG.md
tests/unit/test_kernels.py

- Bugfix
In current `main`, the sign of the expected gradient for the `PeriodicKernel` is incorrect. However, this wasn't showing up in tests, since it was also evaluating to 0. On Jax 0.5.0, it was no longer evaluating to zero, and so started causing test failures. (See #930;  this PR doesn't fix all the issues there.)
We should probably investigate why the gradient was evaluating to 0, and why it isn't doing so in jax 0.5.0!
The `grad_x` and `grad_y` tests pass with jax 0.5.0. Also, the definitions now match between `TestPeriodicKernel` and `PeriodicKernel`.
No.

fix: correct sign of periodic kernel expected gradient

---

coreax/__init__.py
pyproject.toml

Closes #538.
Existing tests pass as expected.
New tests introduced with this change verify that...
No.

fix: add package API exports in top level `__all__`

---

CHANGELOG.md
coreax/solvers/composite.py

- Bugfix
MapReduce's warning about padding invariance is now raised at the correct stacklevel (so it appears at the call site, rather than in the internals of Equinox.
Have checked the warning is raised at the call site.
No.

fix: stacklevel of MapReduce padding warning

---

.cspell/library_terms.txt
benchmark/mnist_benchmark_visualiser.py
coreax/approximation.py
coreax/coreset.py
coreax/data.py
coreax/least_squares.py
coreax/util.py
documentation/source/ref_style.py
pyproject.toml
tests/coverage/compare.py
tests/performance/cases/normaliser.py
tests/performance/compare.py

Enable Ruff's pyupgrade (UP) rules. These help automatically modernise our code (e.g. using `tuple` over `typing.Tuple`, using `{}` over `dict()`, etc.)
The only manual change made was adding "UP" to the ruff rules list - everything else is an automatic fix by Ruff.
Existing tests pass as expected. `ruff check` passes.
No.

Enable pyupgrade rules

---

.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/performance.yml
.github/workflows/pre_commit_checks.yml
.github/workflows/pyright.yml
.github/workflows/unittests.yml

- Bugfix
This ensures the environment is exactly as we specify in the `uv sync`.
Check log output - no extra packages are being installed.
No.

ci: set `UV_NO_SYNC` to avoid implicit syncs with `uv run`

---

.cspell/library_terms.txt
.github/workflows/coverage.yml
.github/workflows/unittests.yml
pyproject.toml
uv.lock

- Tests
Add pytest-xdist to allow tests to execute in parallel. This should speed up CI.
Existing tests pass as expected. CI is marginally faster.
No.

Add pytest-xdist for parallel test execution

---

.pre-commit-config.yaml

Adds a hook to automatically keep uv.lock up to date with pyproject.toml. Uses the uv-provided hook to keep requirements-doc.txt up-to-date, rather than running our own. 
Importantly, this means that the version of uv that we use is pinned by `.pre-commit-config.yaml`. 
Pre-commit passes.
No.

ci: use uv-provided hooks to keep uv.lock and requirements up-to-date

---

documentation/source/conf.py
pyproject.toml
requirements-doc.txt
uv.lock

In Sphinx 8.2.x, sphinxcontrib-bibtex no longer works with absolute paths to the bibliography file. I _think_ this is a bug, since it worked in Sphinx 8.1.x, so I've reported it at https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/361. However, as an immediate fix, I've ensured that the bibliography file path is relative to the documentation source folder. Closes #989.
Docs build passes; bibliography is present.
No.

Fix compatibility with sphinx 8.2.x

---

CHANGELOG.md
CONTRIBUTING.md
README.md
coreax/__init__.py
coreax/coreset.py
pyproject.toml
tests/unit/test_coreset.py

- Removed beta status
- Removed features deprecated in v0.4.0
- Bumped version number
- Updated CHANGELOG for new version
- [Release action run](https://github.com/gchq/coreax/actions/runs/14084602994)

Release v1.0.0

---

documentation/source/conf.py

- Bugfix
The linkcheck fails for `https://ora.ox.ac.uk` URLs when building documentation in the CI, causing the CI check to fail. In lieu of identifying a suitable workaround, it is neccessary to disable the linkchecks for these specific URLs, to correct the CI status.
N/A
N/A

fix(ci): ignore ora linkcheck.
